<?php if (count($this->tags)): ?>
    <span class="prepend-phrase"><?php echo isset($this->prepend) ? $this->prepend : ""; ?></span>
    <?php foreach ($this->tags as $tag): ?>
        <?php //var_dump($tags); ?>
        <a href="javascript:void(0);" title="<?php echo $tag->descr; ?>">[<?php echo $tag->name; ?>]</a>
        &nbsp;
        &nbsp;
        &nbsp;
    <?php endforeach; ?>
    <br/>
    <br/>
<?php endif; ?>

